import { SurveyRecord, FgdRecord } from '../types';
import { calculateScore, getPriority } from './scoring';

const rawSurveyItems: Array<Omit<SurveyRecord, 'id' | 'score' | 'prioritas'>> = [
  {
    kecamatan: 'Panakkukang',
    kelurahan: 'Pannampu / Sinrijala',
    nama_jalan: 'Jl. A.P. Pettarani (Segmen Flyover - Sultan Alauddin)',
    latitude: -5.155418,
    longitude: 119.439812,
    panjang_m: 4200,
    kelas_jalan: 'Arteri Primer',
    kepadatan_kabel: 'Sangat Tinggi',
    kepadatan_kawasan: 'Sangat Tinggi',
    kepentingan_kawasan: 'Sangat Tinggi',
    kondisi_kabel: 'Sangat Tinggi',
    potensi_jaringan: 'Sangat Tinggi',
    kelayakan_ducting: 'Sangat Layak',
    hambatan: 'Adanya tiang beton FO eksisting rapat dan utilitas pipa PDAM utama',
    jumlah_tiang_telkom: 148,
    jumlah_tiang_pln_pju: 92,
    trotoar: 'Ada',
    drainase: 'Ada',
    kawasan: 'Komersial / CBD / Pusat Perkantoran Pemerintahan',
    sumber_data: 'Ground Check',
    status_verifikasi: 'Ground Checked',
    surveyor: 'Tim Teknis Kokek Konsulting & APJATEL',
    tanggal_survey: '2026-08-15',
    catatan: 'Prioritas tertinggi penataan ducting kota, koridor percontohan Tol Layang Pettarani.',
    photo_path: 'https://images.unsplash.com/photo-1508873696983-2df5293cb32b?auto=format&fit=crop&w=800&q=80',
  },
  {
    kecamatan: 'Ujung Pandang',
    kelurahan: 'Losari',
    nama_jalan: 'Jl. Penghibur (Kawasan Pantai Losari)',
    latitude: -5.142921,
    longitude: 119.406122,
    panjang_m: 1600,
    kelas_jalan: 'Arteri Sekunder',
    kepadatan_kabel: 'Sangat Tinggi',
    kepadatan_kawasan: 'Sangat Tinggi',
    kepentingan_kawasan: 'Sangat Tinggi',
    kondisi_kabel: 'Tinggi',
    potensi_jaringan: 'Sangat Tinggi',
    kelayakan_ducting: 'Sangat Layak',
    hambatan: 'Kepadatan pengunjung wisata sore-malam, pohon perindang trotoar',
    jumlah_tiang_telkom: 56,
    jumlah_tiang_pln_pju: 42,
    trotoar: 'Ada',
    drainase: 'Ada',
    kawasan: 'Pariwisata / Waterfront Icon Makassar',
    sumber_data: 'Ground Check',
    status_verifikasi: 'FGD-1 Validated',
    surveyor: 'Ahmad & Risaldi',
    tanggal_survey: '2026-08-18',
    catatan: 'Estetika pariwisata prioritas mendesak, kabel melintang merusak pemandangan sunset.',
    photo_path: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80',
  },
  {
    kecamatan: 'Ujung Pandang',
    kelurahan: 'Maloku / Baru',
    nama_jalan: 'Jl. Somba Opu',
    latitude: -5.138402,
    longitude: 119.407981,
    panjang_m: 1350,
    kelas_jalan: 'Kolektor Primer',
    kepadatan_kabel: 'Sangat Tinggi',
    kepadatan_kawasan: 'Sangat Tinggi',
    kepentingan_kawasan: 'Sangat Tinggi',
    kondisi_kabel: 'Sangat Tinggi',
    potensi_jaringan: 'Tinggi',
    kelayakan_ducting: 'Layak',
    hambatan: 'Jalan searah padat pertokoan emas & kuliner khas, ruang bawah tanah sempit',
    jumlah_tiang_telkom: 64,
    jumlah_tiang_pln_pju: 38,
    trotoar: 'Ada',
    drainase: 'Ada',
    kawasan: 'Komersial / Pusat Oleh-oleh & Heritage',
    sumber_data: 'Ground Check',
    status_verifikasi: 'Ground Checked',
    surveyor: 'Budi Santoso',
    tanggal_survey: '2026-08-19',
    catatan: 'Kabel optik bertumpuk lebih dari 30 tarikan per tiang.',
    photo_path: 'https://images.unsplash.com/photo-1477959858617-67f30bc75b82?auto=format&fit=crop&w=800&q=80',
  },
  {
    kecamatan: 'Panakkukang',
    kelurahan: 'Masale / Pandang',
    nama_jalan: 'Jl. Boulevard Panakkukang',
    latitude: -5.152844,
    longitude: 119.447335,
    panjang_m: 2100,
    kelas_jalan: 'Kolektor Primer',
    kepadatan_kabel: 'Sangat Tinggi',
    kepadatan_kawasan: 'Sangat Tinggi',
    kepentingan_kawasan: 'Sangat Tinggi',
    kondisi_kabel: 'Tinggi',
    potensi_jaringan: 'Sangat Tinggi',
    kelayakan_ducting: 'Sangat Layak',
    hambatan: 'Parkir bahu jalan dan aktivitas bongkar muat toko/mall',
    jumlah_tiang_telkom: 78,
    jumlah_tiang_pln_pju: 54,
    trotoar: 'Ada',
    drainase: 'Ada',
    kawasan: 'Komersial & Bisnis Panakkukang',
    sumber_data: 'Ground Check',
    status_verifikasi: 'FGD-2 Final Recommendation',
    surveyor: 'Hendri & Tim GIS',
    tanggal_survey: '2026-08-20',
    catatan: 'Kawasan pusat belanja Mal Panakkukang, kebutuhan bandwidth sangat tinggi.',
    photo_path: '',
  },
  {
    kecamatan: 'Panakkukang',
    kelurahan: 'Karampuang',
    nama_jalan: 'Jl. Urip Sumoharjo',
    latitude: -5.138812,
    longitude: 119.445218,
    panjang_m: 4800,
    kelas_jalan: 'Arteri Primer',
    kepadatan_kabel: 'Tinggi',
    kepadatan_kawasan: 'Sangat Tinggi',
    kepentingan_kawasan: 'Sangat Tinggi',
    kondisi_kabel: 'Tinggi',
    potensi_jaringan: 'Sangat Tinggi',
    kelayakan_ducting: 'Layak',
    hambatan: 'Arus lalu lintas sangat padat, koridor bus Trans Mamminasata',
    jumlah_tiang_telkom: 165,
    jumlah_tiang_pln_pju: 110,
    trotoar: 'Ada',
    drainase: 'Ada',
    kawasan: 'Pusat Pemerintahan Provinsi & RSUD Wahidin / UMI',
    sumber_data: 'Ground Check',
    status_verifikasi: 'Ground Checked',
    surveyor: 'Kurniawan',
    tanggal_survey: '2026-08-21',
    catatan: 'Penyeberangan kabel antar ruas jalan utama butuh crossing microtunnelling.',
    photo_path: '',
  },
  {
    kecamatan: 'Ujung Pandang',
    kelurahan: 'Mangkura',
    nama_jalan: 'Jl. Jenderal Sudirman',
    latitude: -5.143211,
    longitude: 119.414772,
    panjang_m: 2300,
    kelas_jalan: 'Arteri Sekunder',
    kepadatan_kabel: 'Tinggi',
    kepadatan_kawasan: 'Sangat Tinggi',
    kepentingan_kawasan: 'Sangat Tinggi',
    kondisi_kabel: 'Sedang',
    potensi_jaringan: 'Tinggi',
    kelayakan_ducting: 'Sangat Layak',
    hambatan: 'Pohon pelindung asam jawa berakar besar di pinggir trotoar',
    jumlah_tiang_telkom: 68,
    jumlah_tiang_pln_pju: 46,
    trotoar: 'Ada',
    drainase: 'Ada',
    kawasan: 'Pusat Militer, Perbankan, & Kantor Gubernur',
    sumber_data: 'Desk Survey',
    status_verifikasi: 'FGD-1 Validated',
    surveyor: 'Google Maps / Desk',
    tanggal_survey: '2026-08-12',
    catatan: 'Koridor protokoler utama Kota Makassar.',
    photo_path: '',
  },
  {
    kecamatan: 'Rappocini',
    kelurahan: 'Kassi-Kassi / Tidung',
    nama_jalan: 'Jl. Letjen Hertasning',
    latitude: -5.168391,
    longitude: 119.452912,
    panjang_m: 3600,
    kelas_jalan: 'Arteri Sekunder',
    kepadatan_kabel: 'Tinggi',
    kepadatan_kawasan: 'Tinggi',
    kepentingan_kawasan: 'Tinggi',
    kondisi_kabel: 'Sedang',
    potensi_jaringan: 'Tinggi',
    kelayakan_ducting: 'Sangat Layak',
    hambatan: 'Median jalan lebar, saluran drainase terbuka di beberapa titik',
    jumlah_tiang_telkom: 95,
    jumlah_tiang_pln_pju: 72,
    trotoar: 'Ada',
    drainase: 'Ada',
    kawasan: 'Hunian Menengah Atas & Bisnis Baru',
    sumber_data: 'Ground Check',
    status_verifikasi: 'Ground Checked',
    surveyor: 'Fajar Nugraha',
    tanggal_survey: '2026-08-22',
    catatan: 'Koneksi vital Makassar menuju Kabupaten Gowa.',
    photo_path: '',
  },
  {
    kecamatan: 'Mariso',
    kelurahan: 'Kunjung Mae',
    nama_jalan: 'Jl. Dr. Ratulangi',
    latitude: -5.150212,
    longitude: 119.414018,
    panjang_m: 2200,
    kelas_jalan: 'Arteri Sekunder',
    kepadatan_kabel: 'Tinggi',
    kepadatan_kawasan: 'Tinggi',
    kepentingan_kawasan: 'Tinggi',
    kondisi_kabel: 'Tinggi',
    potensi_jaringan: 'Tinggi',
    kelayakan_ducting: 'Layak',
    hambatan: 'Pertokoan dan sekolah padat jam masuk/pulang',
    jumlah_tiang_telkom: 74,
    jumlah_tiang_pln_pju: 48,
    trotoar: 'Ada',
    drainase: 'Ada',
    kawasan: 'Pendidikan & Rumah Sakit (Labuang Baji)',
    sumber_data: 'Desk Survey',
    status_verifikasi: 'Desk Only',
    surveyor: 'Google Maps / Desk',
    tanggal_survey: '2026-08-10',
    catatan: 'Perlu validasi ground check untuk titik rawan crossing kabel.',
    photo_path: '',
  },
  {
    kecamatan: 'Mamajang',
    kelurahan: 'Maricaya Selatan',
    nama_jalan: 'Jl. Veteran Selatan',
    latitude: -5.159382,
    longitude: 119.421884,
    panjang_m: 2900,
    kelas_jalan: 'Kolektor Sekunder',
    kepadatan_kabel: 'Sangat Tinggi',
    kepadatan_kawasan: 'Tinggi',
    kepentingan_kawasan: 'Sedang',
    kondisi_kabel: 'Sangat Tinggi',
    potensi_jaringan: 'Sedang',
    kelayakan_ducting: 'Cukup',
    hambatan: 'Kerapatan bangunan rapat ke bahu jalan, trotoar sempit',
    jumlah_tiang_telkom: 112,
    jumlah_tiang_pln_pju: 64,
    trotoar: 'Ada',
    drainase: 'Ada',
    kawasan: 'Komersial Otomotif & Pertokoan',
    sumber_data: 'Desk Survey',
    status_verifikasi: 'Desk Only',
    surveyor: 'Google Maps / Desk',
    tanggal_survey: '2026-08-10',
    catatan: 'Banyak tarikan kabel dropcore semrawut melorot di bawah 4 meter.',
    photo_path: '',
  },
  {
    kecamatan: 'Tamalanrea',
    kelurahan: 'Tamalanrea Indah',
    nama_jalan: 'Jl. Perintis Kemerdekaan (Kawasan UNHAS - BTP)',
    latitude: -5.132849,
    longitude: 119.489122,
    panjang_m: 5500,
    kelas_jalan: 'Arteri Primer',
    kepadatan_kabel: 'Sedang',
    kepadatan_kawasan: 'Tinggi',
    kepentingan_kawasan: 'Sangat Tinggi',
    kondisi_kabel: 'Sedang',
    potensi_jaringan: 'Sangat Tinggi',
    kelayakan_ducting: 'Sangat Layak',
    hambatan: 'Panjang koridor dan crossing underpass Mandai / Simpang Lima',
    jumlah_tiang_telkom: 140,
    jumlah_tiang_pln_pju: 105,
    trotoar: 'Ada',
    drainase: 'Ada',
    kawasan: 'Pusat Pendidikan Tinggi (UNHAS, UIM, PNUP) & Gerbang Kota',
    sumber_data: 'Ground Check',
    status_verifikasi: 'Ground Checked',
    surveyor: 'Syaiful Rahmat',
    tanggal_survey: '2026-08-23',
    catatan: 'Kapasitas subduct direkomendasikan minimal 6 way multi-duct.',
    photo_path: '',
  },
  {
    kecamatan: 'Wajo',
    kelurahan: 'Pattunuang',
    nama_jalan: 'Jl. Nusantara (Pelabuhan Soekarno-Hatta)',
    latitude: -5.124911,
    longitude: 119.408221,
    panjang_m: 1800,
    kelas_jalan: 'Kolektor Primer',
    kepadatan_kabel: 'Tinggi',
    kepadatan_kawasan: 'Sedang',
    kepentingan_kawasan: 'Tinggi',
    kondisi_kabel: 'Tinggi',
    potensi_jaringan: 'Tinggi',
    kelayakan_ducting: 'Layak',
    hambatan: 'Truk kontainer besar melintas, koridor pelabuhan ekspor impor',
    jumlah_tiang_telkom: 52,
    jumlah_tiang_pln_pju: 40,
    trotoar: 'Ada',
    drainase: 'Ada',
    kawasan: 'Logistik & Pelabuhan Laut Nasional',
    sumber_data: 'Desk Survey',
    status_verifikasi: 'FGD-1 Validated',
    surveyor: 'Google Maps / Desk',
    tanggal_survey: '2026-08-11',
    catatan: 'Sering insiden kabel putus tersangkut kontainer tinggi.',
    photo_path: '',
  },
  {
    kecamatan: 'Bontoala',
    kelurahan: 'Wajo Baru / Gaddong',
    nama_jalan: 'Jl. Mesjid Raya',
    latitude: -5.132144,
    longitude: 119.423981,
    panjang_m: 1400,
    kelas_jalan: 'Kolektor Primer',
    kepadatan_kabel: 'Tinggi',
    kepadatan_kawasan: 'Tinggi',
    kepentingan_kawasan: 'Tinggi',
    kondisi_kabel: 'Tinggi',
    potensi_jaringan: 'Sedang',
    kelayakan_ducting: 'Layak',
    hambatan: 'Aktivitas pasar dan jamaah masjid raya pada hari besar',
    jumlah_tiang_telkom: 48,
    jumlah_tiang_pln_pju: 32,
    trotoar: 'Ada',
    drainase: 'Ada',
    kawasan: 'Religi & Perdagangan Tradisional',
    sumber_data: 'Desk Survey',
    status_verifikasi: 'Desk Only',
    surveyor: 'Google Maps / Desk',
    tanggal_survey: '2026-08-12',
    catatan: 'Perlu pemindahan bertahap tiang utilitas di sisi kanan jalan.',
    photo_path: '',
  },
  {
    kecamatan: 'Tamalate',
    kelurahan: 'Pa’baeng-baeng',
    nama_jalan: 'Jl. Sultan Alauddin',
    latitude: -5.176412,
    longitude: 119.431284,
    panjang_m: 3100,
    kelas_jalan: 'Arteri Primer',
    kepadatan_kabel: 'Tinggi',
    kepadatan_kawasan: 'Tinggi',
    kepentingan_kawasan: 'Tinggi',
    kondisi_kabel: 'Sedang',
    potensi_jaringan: 'Tinggi',
    kelayakan_ducting: 'Layak',
    hambatan: 'Kemacetan simpang pertigaan pettarani-alauddin',
    jumlah_tiang_telkom: 88,
    jumlah_tiang_pln_pju: 58,
    trotoar: 'Ada',
    drainase: 'Ada',
    kawasan: 'Komersial & Kampus (UNM Gunung Sari)',
    sumber_data: 'Ground Check',
    status_verifikasi: 'Ground Checked',
    surveyor: 'Zulkifli',
    tanggal_survey: '2026-08-24',
    catatan: 'Integrasi dengan jalur perbatasan Sungguminasa Gowa.',
    photo_path: '',
  },
  {
    kecamatan: 'Manggala',
    kelurahan: 'Antang',
    nama_jalan: 'Jl. Antang Raya',
    latitude: -5.161042,
    longitude: 119.479102,
    panjang_m: 2800,
    kelas_jalan: 'Kolektor Sekunder',
    kepadatan_kabel: 'Sedang',
    kepadatan_kawasan: 'Sedang',
    kepentingan_kawasan: 'Sedang',
    kondisi_kabel: 'Sedang',
    potensi_jaringan: 'Sedang',
    kelayakan_ducting: 'Cukup',
    hambatan: 'Sebagian drainase sempit dan rawan genangan musiman',
    jumlah_tiang_telkom: 62,
    jumlah_tiang_pln_pju: 44,
    trotoar: 'Tidak Ada',
    drainase: 'Ada',
    kawasan: 'Pemukiman & Sentra Pasar Antang',
    sumber_data: 'Desk Survey',
    status_verifikasi: 'Desk Only',
    surveyor: 'Google Maps / Desk',
    tanggal_survey: '2026-08-11',
    catatan: 'Penataan kabel menunggu pelebaran jalan Pemprov Sulsel.',
    photo_path: '',
  },
  {
    kecamatan: 'Tallo',
    kelurahan: 'Buloa',
    nama_jalan: 'Jl. Galangan Kapal',
    latitude: -5.118944,
    longitude: 119.434821,
    panjang_m: 1500,
    kelas_jalan: 'Lokal',
    kepadatan_kabel: 'Rendah',
    kepadatan_kawasan: 'Sedang',
    kepentingan_kawasan: 'Rendah',
    kondisi_kabel: 'Rendah',
    potensi_jaringan: 'Rendah',
    kelayakan_ducting: 'Kurang',
    hambatan: 'Dekat muara sungai, tanah berpasir/rawa',
    jumlah_tiang_telkom: 28,
    jumlah_tiang_pln_pju: 22,
    trotoar: 'Tidak Ada',
    drainase: 'Ada',
    kawasan: 'Industri Maritim & Pemukiman Nelayan',
    sumber_data: 'Desk Survey',
    status_verifikasi: 'Desk Only',
    surveyor: 'Google Maps / Desk',
    tanggal_survey: '2026-08-10',
    catatan: 'Prioritas jangka panjang (P4).',
    photo_path: '',
  },
];

export function getInitialSurveyRecords(): SurveyRecord[] {
  return rawSurveyItems.map((item, idx) => {
    const score = calculateScore(item);
    const prioritas = getPriority(score);
    return {
      id: `survey-mks-${idx + 101}`,
      ...item,
      score,
      prioritas,
    };
  });
}

export function getInitialFgdRecords(): FgdRecord[] {
  return [
    {
      id: 'fgd-001',
      session: 'FGD-1',
      tanggal: '2026-08-14',
      stakeholder: 'Kokek Konsulting, APJATEL Sulsel',
      isu: 'Kepadatan kabel udara di Jl. A.P. Pettarani mencapai titik kritis setelah pengoperasian Tol Layang.',
      koridor: 'Jl. A.P. Pettarani (Segmen Flyover - Sultan Alauddin)',
      keputusan: 'Disepakati sebagai Ruas Prioritas Utama (Pilot Project 2026) skema KPBU / Sewa Ducting Bersama.',
      tindak_lanjut: 'Ground check detail utilitas bawah tanah dan inventarisasi tiang Telkom & PLN.',
      status: 'Validated',
      catatan: 'APJATEL siap mendukung cut-over kabel jika ducting terintegrasi rampung.',
    },
    {
      id: 'fgd-002',
      session: 'FGD-1',
      tanggal: '2026-08-16',
      stakeholder: 'Dinas Pariwisata, Diskominfo, Asosiasi Pengusaha Hotel Losari',
      isu: 'Estetika Pantai Losari terganggu bentangan kabel optik antar tiang di Jl. Penghibur dan Somba Opu.',
      koridor: 'Jl. Penghibur (Kawasan Pantai Losari)',
      keputusan: 'Validasi koridor wisata super prioritas. Wajib underground kabel optik.',
      tindak_lanjut: 'Koordinasi perizinan penggalian dengan Dinas Tata Ruang & Balai Jalan.',
      status: 'Validated',
      catatan: 'Target bebas kabel udara sebelum Festival F8 Makassar.',
    },
    {
      id: 'fgd-003',
      session: 'FGD-1',
      tanggal: '2026-08-17',
      stakeholder: 'Balai Besar Pelaksanaan Jalan Nasional (BBPJN) Sulsel & Dishub',
      isu: 'Kerapatan tiang utilitas di Jl. Perintis Kemerdekaan mengganggu ruang pejalan kaki.',
      koridor: 'Jl. Perintis Kemerdekaan (Kawasan UNHAS - BTP)',
      keputusan: 'Diperlukan ground check pengukuran span kabel dan penentuan lokasi manhole terpadu.',
      tindak_lanjut: 'Tim teknis gabungan turun ke lapangan tanggal 23 Agustus.',
      status: 'Need Ground Check',
      catatan: 'Jalan nasional memerlukan sinkronisasi regulasi pemanfaatan ruang milik jalan (RUMIJA).',
    },
    {
      id: 'fgd-004',
      session: 'FGD-2',
      tanggal: '2026-08-26',
      stakeholder: 'Bappeda Makassar, PT PLN UID Sulselrabar, PT Telkom Witel Sulsel, APJATEL',
      isu: 'Hasil ground check Jl. Boulevard Panakkukang membuktikan kelayakan ducting tipe pipa HDPE 4-way subduct.',
      koridor: 'Jl. Boulevard Panakkukang',
      keputusan: 'Ditetapkan rekomendasi final: Pembangunan Box Culvert Micro-trenching bersama.',
      tindak_lanjut: 'Penyusunan DED (Detail Engineering Design) dan skema tarif sewa bersama per meter/bulan.',
      status: 'Final',
      catatan: 'Telkom dan PLN menyetujui sharing biaya pengawasan teknis instalasi.',
    },
    {
      id: 'fgd-005',
      session: 'FGD-2',
      tanggal: '2026-08-28',
      stakeholder: 'Tim Ahli Smart City Makassar & Inspektorat Kota Makassar',
      isu: 'Rekomendasi teknis penanganan 5 Koridor P1 Kota Makassar.',
      koridor: 'Jl. A.P. Pettarani (Segmen Flyover - Sultan Alauddin)',
      keputusan: 'Pengesahan Kajian Master Ducting Terpadu V4 untuk diajukan ke Walikota Makassar.',
      tindak_lanjut: 'Penerbitan Peraturan Walikota (Perwali) Penataan Kabel Bawah Tanah Terpadu.',
      status: 'Final',
      catatan: 'Dokumen kajian master siap diexport sebagai lampiran naskah akademik.',
    },
  ];
}
